#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-TimeDate
Version  : 2.33
Release  : 31
URL      : https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/TimeDate-2.33.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/TimeDate-2.33.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-TimeDate-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is the perl5 TimeDate distribution. It requires perl version 5.003
or later

%package dev
Summary: dev components for the perl-TimeDate package.
Group: Development
Provides: perl-TimeDate-devel = %{version}-%{release}
Requires: perl-TimeDate = %{version}-%{release}

%description dev
dev components for the perl-TimeDate package.


%package perl
Summary: perl components for the perl-TimeDate package.
Group: Default
Requires: perl-TimeDate = %{version}-%{release}

%description perl
perl components for the perl-TimeDate package.


%prep
%setup -q -n TimeDate-2.33
cd %{_builddir}/TimeDate-2.33

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Date::Format.3
/usr/share/man/man3/Date::Language.3
/usr/share/man/man3/Date::Language::Bulgarian.3
/usr/share/man/man3/Date::Language::Hungarian.3
/usr/share/man/man3/Date::Parse.3
/usr/share/man/man3/Time::Zone.3
/usr/share/man/man3/TimeDate.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
